default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: db
  timeout: 5000

development:
  <<: *default
  database: parking-db-development

# Warning: The database defined as "test" will be erased and
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: parking-db-test

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
